### ISSUE TITLE
Refactor config file to include all the things needed

### ISSUE THREAD

**Issue by epsxy** [epsxy/gommitizen#17]
Commit length? what else? This will require a new version as it will introduce breaking changes. Will require to update the documentation with the new script syntax.

Ideas:

```
commit:
    length: 80
    types:
        - first
        - second
    scopes:
        - first
        - second
lint:
    whitelist:
        - "/^Merge pull request"
        - "/^Revert pull request"
changelog:
    include:
        - first
        - second
    exclude:
        - first
        - second
release:
    template: "chore: release version"
```
